image_width: 640
image_height: 480
camera_name: ov5647
camera_matrix:
  rows: 3
  cols: 3
  data:
  - 313.91747355381085
  - 0.0
  - 315.8852043995971
  - 0.0
  - 315.4740065983454
  - 228.22917068648076
  - 0.0
  - 0.0
  - 1.0
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data:
  - -0.3373208315541661
  - 0.13760055018502604
  - -0.00018906758580775605
  - -7.269970629010719e-06
  - -0.028500188681027255
rectification_matrix:
  rows: 3
  cols: 3
  data:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
projection_matrix:
  rows: 3
  cols: 4
  data:
  - 313.91747355381085
  - 0.0
  - 315.8852043995971
  - 0.0
  - 0.0
  - 315.4740065983454
  - 228.22917068648076
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
# RMSE 0.700278 px